# Basic Information
title: Jiashuo Zhang
name_chinese: 张家硕
position:
affiliation: Johns Hopkins University
email: jzhan427 (at) jhu.edu

# SEO
keywords: Jiashuo Zhang, Johns Hopkins, AI, biomedical, healthcare, machine learning
description: Personal academic homepage of Jiashuo Zhang, Research Assistant at Johns Hopkins University.
canonical: https://sethzhangjs.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=ao8Tf0gAAAAJ&hl=en
github_link: https://github.com/sethzhangjs
linkedin: https://www.linkedin.com/in/sethzhangjs
orcid: https://orcid.org/my-orcid?orcid=0009-0006-2838-3519

# Images
avatar: ./images/sethzhangjs_profile.JPG
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Options
enable_footnote: true
auto_dark_mode: true
font: "Serif"

# Use minimal-light as remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - _drafts
  - _portfolio
  - _posts
  - _talks
  - _teaching
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - markdown_generator
