# Basic Information
title: Jiashuo Zhang
name_chinese: 张家硕
position:
affiliation: Johns Hopkins University
email: jzhan427 (at) jhu.edu
email_personal: sethzhangjs (at) gmail.com
location: Baltimore, MD, USA

# SEO
keywords: Jiashuo Zhang, Johns Hopkins, JHU, AI, healthcare, machine learning, deep learning, bioinformatics, 张家硕, 山东大学
description: Personal academic homepage of Jiashuo Zhang.
canonical: https://sethzhangjs.github.io/
url: https://sethzhangjs.github.io

# Links
orcid: https://orcid.org/0009-0006-2838-3519
google_scholar: https://scholar.google.com/citations?user=ao8Tf0gAAAAJ&hl=en
github_link: https://github.com/sethzhangjs
linkedin: https://www.linkedin.com/in/sethzhangjs
dblp: https://dblp.org/pid/211/9458-2.html
semantic_scholar: https://www.semanticscholar.org/author/Jiashuo-Zhang/2273899142
cv_link: https://drive.google.com/file/d/14wW3ByJH_BXQqMjxD_PgEGNt_HVO7wqO/view?usp=sharing
x_link: https://x.com/sethzhangjs


# Images
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Options
enable_footnote: true
auto_dark_mode: true
font: "Serif"

# Use minimal-light as remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - _drafts
  - _portfolio
  - _posts
  - _talks
  - _teaching
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - markdown_generator
